  version: '3'
  services: 
    player-auction: 
      image: player-auction
      build: .
      ports: 
        - "8080:8080" 
      restart: always
      environment:
         SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/player_auction?useSSL=false 
         SPRING_DATASOURCE_USERNAME: "root"
         SPRING_DATASOURCE_PASSWORD: "root"
      build: 
        context: "./"
        dockerfile: "Dockerfile"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
      depends_on:
        - mysql-standalone        
        
        
    mysql-standalone:
      image: mysql:5.6
      restart: always
      ports: 
        - "3309:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_PASSWORD=root
        - MYSQL_DATABASE=player_auction
 #docker-compose -f docker-compose.yml up      
      
                    
                